[2024-05-17T16:15:44.317+0530] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: iris_classification.train_model manual__2024-05-17T10:45:29.500408+00:00 [queued]>
[2024-05-17T16:15:44.319+0530] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: iris_classification.train_model manual__2024-05-17T10:45:29.500408+00:00 [queued]>
[2024-05-17T16:15:44.320+0530] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-05-17T16:15:44.325+0530] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): train_model> on 2024-05-17 10:45:29.500408+00:00
[2024-05-17T16:15:44.328+0530] {standard_task_runner.py:57} INFO - Started process 32433 to run task
[2024-05-17T16:15:44.329+0530] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-05-17T16:15:44.335+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'iris_classification', 'train_model', 'manual__2024-05-17T10:45:29.500408+00:00', '--job-id', '12', '--raw', '--subdir', 'DAGS_FOLDER/iris_prediction.py', '--cfg-path', '/var/folders/fy/4q0txy357vvc35bhsxlfyr8c0000gn/T/tmpo68ux725']
[2024-05-17T16:15:44.338+0530] {standard_task_runner.py:85} INFO - Job 12: Subtask train_model
[2024-05-17T16:15:44.361+0530] {task_command.py:410} INFO - Running <TaskInstance: iris_classification.train_model manual__2024-05-17T10:45:29.500408+00:00 [running]> on host aswins-macbook-air.local
[2024-05-17T16:15:44.380+0530] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='iris_classification' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2024-05-17T10:45:29.500408+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-17T10:45:29.500408+00:00'
[2024-05-17T16:15:45.800+0530] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/aswin/anaconda3/envs/bdl/lib/python3.10/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/Users/aswin/anaconda3/envs/bdl/lib/python3.10/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/Users/aswin/Downloads/Courses/Big Data Lab/Project/dags/iris_prediction.py", line 74, in train_model
    mlflow.log_artifact("preprocessed_data.parquet", artifact_path="data")
  File "/Users/aswin/anaconda3/envs/bdl/lib/python3.10/site-packages/mlflow/tracking/fluent.py", line 1068, in log_artifact
    MlflowClient().log_artifact(run_id, local_path, artifact_path)
  File "/Users/aswin/anaconda3/envs/bdl/lib/python3.10/site-packages/mlflow/tracking/client.py", line 1215, in log_artifact
    self._tracking_client.log_artifact(run_id, local_path, artifact_path)
  File "/Users/aswin/anaconda3/envs/bdl/lib/python3.10/site-packages/mlflow/tracking/_tracking_service/client.py", line 557, in log_artifact
    artifact_repo.log_artifact(local_path, artifact_path)
  File "/Users/aswin/anaconda3/envs/bdl/lib/python3.10/site-packages/mlflow/store/artifact/local_artifact_repo.py", line 39, in log_artifact
    shutil.copy2(local_file, os.path.join(artifact_dir, os.path.basename(local_file)))
  File "/Users/aswin/anaconda3/envs/bdl/lib/python3.10/shutil.py", line 434, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/Users/aswin/anaconda3/envs/bdl/lib/python3.10/shutil.py", line 254, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: 'preprocessed_data.parquet'
[2024-05-17T16:15:45.807+0530] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=iris_classification, task_id=train_model, execution_date=20240517T104529, start_date=20240517T104544, end_date=20240517T104545
[2024-05-17T16:15:45.811+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 12 for task train_model ([Errno 2] No such file or directory: 'preprocessed_data.parquet'; 32433)
[2024-05-17T16:15:45.820+0530] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-05-17T16:15:45.825+0530] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
