[2024-05-17T15:47:30.128+0530] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: iris_classification.preprocess_data manual__2024-05-17T10:17:24.803284+00:00 [queued]>
[2024-05-17T15:47:30.130+0530] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: iris_classification.preprocess_data manual__2024-05-17T10:17:24.803284+00:00 [queued]>
[2024-05-17T15:47:30.130+0530] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-05-17T15:47:30.135+0530] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): preprocess_data> on 2024-05-17 10:17:24.803284+00:00
[2024-05-17T15:47:30.138+0530] {standard_task_runner.py:57} INFO - Started process 24324 to run task
[2024-05-17T15:47:30.139+0530] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-05-17T15:47:30.142+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'iris_classification', 'preprocess_data', 'manual__2024-05-17T10:17:24.803284+00:00', '--job-id', '7', '--raw', '--subdir', 'DAGS_FOLDER/iris_prediction.py', '--cfg-path', '/var/folders/fy/4q0txy357vvc35bhsxlfyr8c0000gn/T/tmpgrvhk3d1']
[2024-05-17T15:47:30.143+0530] {standard_task_runner.py:85} INFO - Job 7: Subtask preprocess_data
[2024-05-17T15:47:30.171+0530] {task_command.py:410} INFO - Running <TaskInstance: iris_classification.preprocess_data manual__2024-05-17T10:17:24.803284+00:00 [running]> on host aswins-macbook-air.local
[2024-05-17T15:47:30.190+0530] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='iris_classification' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-17T10:17:24.803284+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-17T10:17:24.803284+00:00'
[2024-05-17T15:47:30.740+0530] {clientserver.py:505} INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/Users/aswin/anaconda3/envs/bdl/lib/python3.10/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
BrokenPipeError: [Errno 32] Broken pipe
[2024-05-17T15:47:30.743+0530] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-05-17T15:47:30.743+0530] {java_gateway.py:1052} INFO - Exception while sending command.
Traceback (most recent call last):
  File "/Users/aswin/anaconda3/envs/bdl/lib/python3.10/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aswin/anaconda3/envs/bdl/lib/python3.10/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/Users/aswin/anaconda3/envs/bdl/lib/python3.10/site-packages/py4j/clientserver.py", line 506, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
[2024-05-17T15:47:30.745+0530] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-05-17T15:47:32.632+0530] {python.py:183} INFO - Done. Returned value was: {'train': DataFrame[sepal_length: double, sepal_width: double, petal_length: double, petal_width: double, label: string, features: vector], 'test': DataFrame[sepal_length: double, sepal_width: double, petal_length: double, petal_width: double, label: string, features: vector]}
[2024-05-17T15:47:32.643+0530] {xcom.py:634} ERROR - Object of type DataFrame is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your airflow config or make sure to decorate your object with attr.
[2024-05-17T15:47:32.643+0530] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/Users/aswin/anaconda3/envs/bdl/lib/python3.10/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
  File "/Users/aswin/anaconda3/envs/bdl/lib/python3.10/site-packages/airflow/serialization/serde.py", line 171, in serialize
    raise TypeError(f"cannot serialize object of type {cls}")
TypeError: cannot serialize object of type <class 'pyspark.sql.dataframe.DataFrame'>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aswin/anaconda3/envs/bdl/lib/python3.10/site-packages/airflow/utils/session.py", line 73, in wrapper
    return func(*args, **kwargs)
  File "/Users/aswin/anaconda3/envs/bdl/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2354, in xcom_push
    XCom.set(
  File "/Users/aswin/anaconda3/envs/bdl/lib/python3.10/site-packages/airflow/utils/session.py", line 73, in wrapper
    return func(*args, **kwargs)
  File "/Users/aswin/anaconda3/envs/bdl/lib/python3.10/site-packages/airflow/models/xcom.py", line 237, in set
    value = cls.serialize_value(
  File "/Users/aswin/anaconda3/envs/bdl/lib/python3.10/site-packages/airflow/models/xcom.py", line 632, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/Users/aswin/anaconda3/envs/bdl/lib/python3.10/json/__init__.py", line 238, in dumps
    **kw).encode(obj)
  File "/Users/aswin/anaconda3/envs/bdl/lib/python3.10/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
  File "/Users/aswin/anaconda3/envs/bdl/lib/python3.10/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/Users/aswin/anaconda3/envs/bdl/lib/python3.10/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/Users/aswin/anaconda3/envs/bdl/lib/python3.10/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
  File "/Users/aswin/anaconda3/envs/bdl/lib/python3.10/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
[2024-05-17T15:47:32.648+0530] {taskinstance.py:1345} INFO - Marking task as UP_FOR_RETRY. dag_id=iris_classification, task_id=preprocess_data, execution_date=20240517T101724, start_date=20240517T101730, end_date=20240517T101732
[2024-05-17T15:47:32.651+0530] {standard_task_runner.py:104} ERROR - Failed to execute job 7 for task preprocess_data (Object of type DataFrame is not JSON serializable; 24324)
[2024-05-17T15:47:32.667+0530] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2024-05-17T15:47:32.675+0530] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
