[2024-05-18T02:07:45.086+0530] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: iris_classification.train_model manual__2024-05-17T20:37:30.996464+00:00 [queued]>
[2024-05-18T02:07:45.088+0530] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: iris_classification.train_model manual__2024-05-17T20:37:30.996464+00:00 [queued]>
[2024-05-18T02:07:45.088+0530] {taskinstance.py:1308} INFO - Starting attempt 1 of 0
[2024-05-18T02:07:45.093+0530] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): train_model> on 2024-05-17 20:37:30.996464+00:00
[2024-05-18T02:07:45.097+0530] {standard_task_runner.py:57} INFO - Started process 3224 to run task
[2024-05-18T02:07:45.098+0530] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-05-18T02:07:45.101+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'iris_classification', 'train_model', 'manual__2024-05-17T20:37:30.996464+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/var/folders/fy/4q0txy357vvc35bhsxlfyr8c0000gn/T/tmp025d9cgo']
[2024-05-18T02:07:45.102+0530] {standard_task_runner.py:85} INFO - Job 58: Subtask train_model
[2024-05-18T02:07:45.122+0530] {task_command.py:410} INFO - Running <TaskInstance: iris_classification.train_model manual__2024-05-17T20:37:30.996464+00:00 [running]> on host aswins-macbook-air.local
[2024-05-18T02:07:45.151+0530] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='iris_classification' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2024-05-17T20:37:30.996464+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-17T20:37:30.996464+00:00'
[2024-05-18T02:09:25.636+0530] {local_task_job_runner.py:291} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-05-18T02:09:25.641+0530] {process_utils.py:131} INFO - Sending Signals.SIGTERM to group 3224. PIDs of all processes in the group: [3224]
[2024-05-18T02:09:25.641+0530] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 3224
[2024-05-18T02:10:25.666+0530] {process_utils.py:149} WARNING - process psutil.Process(pid=3224, name='python3.10', status='running', started='02:07:45') did not respond to SIGTERM. Trying SIGKILL
[2024-05-18T02:10:25.668+0530] {process_utils.py:86} INFO - Sending the signal Signals.SIGKILL to group 3224
[2024-05-18T02:10:25.684+0530] {process_utils.py:79} INFO - Process psutil.Process(pid=3224, name='python3.10', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='02:07:45') (3224) terminated with exit code Negsignal.SIGKILL
[2024-05-18T02:10:25.684+0530] {standard_task_runner.py:172} ERROR - Job 58 was killed before it finished (likely due to running out of memory)
