[2024-05-18T10:53:20.284+0530] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: iris_classification.train_model manual__2024-05-18T05:23:00.744711+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
