[2024-05-18T01:20:11.747+0530] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: iris_classification.train_model manual__2024-05-17T19:49:54.604377+00:00 [queued]>
[2024-05-18T01:20:11.749+0530] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: iris_classification.train_model manual__2024-05-17T19:49:54.604377+00:00 [queued]>
[2024-05-18T01:20:11.749+0530] {taskinstance.py:1308} INFO - Starting attempt 1 of 0
[2024-05-18T01:20:11.755+0530] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): train_model> on 2024-05-17 19:49:54.604377+00:00
[2024-05-18T01:20:11.759+0530] {standard_task_runner.py:57} INFO - Started process 4525 to run task
[2024-05-18T01:20:11.759+0530] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-05-18T01:20:11.763+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'iris_classification', 'train_model', 'manual__2024-05-17T19:49:54.604377+00:00', '--job-id', '41', '--raw', '--subdir', 'DAGS_FOLDER/main.py', '--cfg-path', '/var/folders/fy/4q0txy357vvc35bhsxlfyr8c0000gn/T/tmpoqbx2yca']
[2024-05-18T01:20:11.765+0530] {standard_task_runner.py:85} INFO - Job 41: Subtask train_model
[2024-05-18T01:20:11.790+0530] {task_command.py:410} INFO - Running <TaskInstance: iris_classification.train_model manual__2024-05-17T19:49:54.604377+00:00 [running]> on host aswins-macbook-air.local
[2024-05-18T01:20:11.815+0530] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='iris_classification' AIRFLOW_CTX_TASK_ID='train_model' AIRFLOW_CTX_EXECUTION_DATE='2024-05-17T19:49:54.604377+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-17T19:49:54.604377+00:00'
[2024-05-18T01:26:33.776+0530] {local_task_job_runner.py:291} WARNING - State of this instance has been externally set to failed. Terminating instance.
[2024-05-18T01:26:33.798+0530] {process_utils.py:131} INFO - Sending Signals.SIGTERM to group 4525. PIDs of all processes in the group: [4525]
[2024-05-18T01:26:33.798+0530] {process_utils.py:86} INFO - Sending the signal Signals.SIGTERM to group 4525
[2024-05-18T01:27:33.836+0530] {process_utils.py:149} WARNING - process psutil.Process(pid=4525, name='python3.10', status='running', started='01:20:11') did not respond to SIGTERM. Trying SIGKILL
[2024-05-18T01:27:33.838+0530] {process_utils.py:86} INFO - Sending the signal Signals.SIGKILL to group 4525
[2024-05-18T01:27:33.854+0530] {process_utils.py:79} INFO - Process psutil.Process(pid=4525, name='python3.10', status='terminated', exitcode=<Negsignal.SIGKILL: -9>, started='01:20:11') (4525) terminated with exit code Negsignal.SIGKILL
[2024-05-18T01:27:33.855+0530] {standard_task_runner.py:172} ERROR - Job 41 was killed before it finished (likely due to running out of memory)
