[2024-05-17T20:35:48.712+0530] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: iris_classification.preprocess_data manual__2024-05-17T15:05:43.517800+00:00 [queued]>
[2024-05-17T20:35:48.715+0530] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: iris_classification.preprocess_data manual__2024-05-17T15:05:43.517800+00:00 [queued]>
[2024-05-17T20:35:48.715+0530] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2024-05-17T20:35:48.720+0530] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): preprocess_data> on 2024-05-17 15:05:43.517800+00:00
[2024-05-17T20:35:48.724+0530] {standard_task_runner.py:57} INFO - Started process 17019 to run task
[2024-05-17T20:35:48.726+0530] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-05-17T20:35:48.730+0530] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'iris_classification', 'preprocess_data', 'manual__2024-05-17T15:05:43.517800+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/iris_prediction.py', '--cfg-path', '/var/folders/fy/4q0txy357vvc35bhsxlfyr8c0000gn/T/tmp56us_zi9']
[2024-05-17T20:35:48.732+0530] {standard_task_runner.py:85} INFO - Job 24: Subtask preprocess_data
[2024-05-17T20:35:48.751+0530] {task_command.py:410} INFO - Running <TaskInstance: iris_classification.preprocess_data manual__2024-05-17T15:05:43.517800+00:00 [running]> on host aswins-macbook-air.local
[2024-05-17T20:35:48.765+0530] {clientserver.py:505} INFO - Error while sending or receiving.
Traceback (most recent call last):
  File "/Users/aswin/anaconda3/envs/bdl/lib/python3.10/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
BrokenPipeError: [Errno 32] Broken pipe
[2024-05-17T20:35:48.767+0530] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-05-17T20:35:48.768+0530] {java_gateway.py:1052} INFO - Exception while sending command.
Traceback (most recent call last):
  File "/Users/aswin/anaconda3/envs/bdl/lib/python3.10/site-packages/py4j/clientserver.py", line 503, in send_command
    self.socket.sendall(command.encode("utf-8"))
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/aswin/anaconda3/envs/bdl/lib/python3.10/site-packages/py4j/java_gateway.py", line 1038, in send_command
    response = connection.send_command(command)
  File "/Users/aswin/anaconda3/envs/bdl/lib/python3.10/site-packages/py4j/clientserver.py", line 506, in send_command
    raise Py4JNetworkError(
py4j.protocol.Py4JNetworkError: Error while sending
[2024-05-17T20:35:48.769+0530] {clientserver.py:543} INFO - Closing down clientserver connection
[2024-05-17T20:35:48.770+0530] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='iris_classification' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-17T15:05:43.517800+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-17T15:05:43.517800+00:00'
[2024-05-17T20:35:52.091+0530] {python.py:183} INFO - Done. Returned value was: None
[2024-05-17T20:35:52.093+0530] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=iris_classification, task_id=preprocess_data, execution_date=20240517T150543, start_date=20240517T150548, end_date=20240517T150552
[2024-05-17T20:35:52.134+0530] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2024-05-17T20:35:52.143+0530] {taskinstance.py:2651} INFO - 1 downstream tasks scheduled from follow-on schedule check
